// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_speedster = "CgkI6Yqw0OMXEAIQBA"; // <GPGSID>
        public const string achievement_mega_fan = "CgkI6Yqw0OMXEAIQAw"; // <GPGSID>
        public const string achievement_eidetic_memory = "CgkI6Yqw0OMXEAIQBg"; // <GPGSID>
        public const string achievement_brainiac = "CgkI6Yqw0OMXEAIQBQ"; // <GPGSID>
        public const string achievement_newbie = "CgkI6Yqw0OMXEAIQAQ"; // <GPGSID>
        public const string achievement_lucky_duck = "CgkI6Yqw0OMXEAIQBw"; // <GPGSID>
        public const string achievement_fanish = "CgkI6Yqw0OMXEAIQAg"; // <GPGSID>

}

